version: "3.9"  # optional since v1.27.0
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    volumes:
      - db-data:/var/lib/postgresql/data/
  trains_db:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: train
    volumes:
      - train-data:/var/lib/postgresql/data/
volumes:
  db-data:
  train-data:

